AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Outputs the time
Resources:
  TimeFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler1
      Runtime: nodejs8.10
      CodeUri: ./
      Events:
        MyTimeApi:
          Type: Api
          Properties:
            Path: /TimeResource
            Method: GET
  HelloWorld:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.handler2
      Runtime: nodejs8.10
      CodeUri: ./
      Description: ''
      MemorySize: 128
      Timeout: 3
      Role: 'arn:aws:iam::564648851972:role/service-role/HelloWorld'
      Events:
        Api1:
          Type: Api
          Properties:
            Path: /HelloWorld
            Method: ANY
